### ISSUE TITLE
Plugin causes Homebridge to crash

### ISSUE THREAD

**Issue by eengert** [huttotw/homebridge-kia-connect#2]
**Describe The Bug:**
As soon as I installed this plugin and restarted, Homebridge won't load - it just keeps shutting itself down and trying to restart.

**To Reproduce:**
Enable Kia plugin and restart Homebridge.

**Logs:**
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at Hash.update (node:internal/crypto/hash:109:11)
    at Object.generate (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at /homebridge/node_modules/homebridge-kia-connect/src/platform.ts:60:38
    at Array.forEach (<anonymous>)
    at Platform.discoverDevices (/homebridge/node_modules/homebridge-kia-connect/src/platform.ts:56:22)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-kia-connect/src/platform.ts:35:12)
    at HomebridgeAPI.emit (node:events:525:35)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/homebridge/node_modules/homebridge/src/server.ts:190:14)

**Plugin Config:**
{
    "bridge": {
        "name": "Homebridge 466D",
        "username": "xxxxxxx",
        "port": 51853,
        "pin": "xxxxxxx",
        "advertiser": "bonjour-hap",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "macAddresses": [
                "xxxxxxxx",
                "xxxxxxxx"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "username": "xxxxxxxxx",
            "password": "xxxxxxxxxx",
            "country": "US",
            "deviceName": "Doorbell",
            "cameras": [
                {
                    "serialNumber": "xxxxxxxx",
                    "rtsp": false,
                    "enableCamera": true,
                    "useCachedLocalLivestream": false,
                    "videoConfig": {
                        "audio": true,
                        "audioSampleRate": 0
                    },
                    "talkback": true,
                    "snapshotHandlingMethod": 3,
                    "refreshSnapshotIntervalMinutes": 10,
                    "unbridge": true,
                    "immediateRingNotificationWithoutSnapshot": true
                }
            ],
            "platform": "EufySecurity",
            "CameraMaxLivestreamDuration": 30,
            "ignoreStations": [],
            "ignoreDevices": [],
            "cleanCache": true,
            "pollingIntervalMinutes": 15
        },
        {
            "name": "B-Hyve Hose Timer",
            "email": "xxxxxxxx",
            "password": "xxxxxxxxxx,
            "defaultRuntime": 30,
            "runtimeSource": 1,
            "useIrrigationDisplay": true,
            "displayValveType": 1,
            "showIrrigation": true,
            "showBridge": false,
            "showFloodSensor": false,
            "showTempSensor": false,
            "showLimitsSensor": false,
            "showStandby": false,
            "showRunall": false,
            "showSchedules": false,
            "showAPIMessages": false,
            "platform": "bhyve"
        },
        {
            "cars": [
                {
                    "name": "Sportage Hybrid",
                    "targetTemperature": "70",
                    "vin": "xxxxxxxxxx",
                    "refreshInterval": 3600000
                },
                {
                    "refreshInterval": 3600000
                }
            ],
            "email": "xxxxxx",
            "password": "xxxxxxxx",
            "platform": "KiaConnect"
        }
    ],
    "disabledPlugins": []
}

**Screenshots:**

**Environment:**

* **Plugin Version**:  1.2.0
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 18.16.1
* **NPM Version**: 
* **Operating System**:  Windows 11 Hyper-V

**Comment by huttotw** [comment]
@eengert sorry for the delay. It looks like you have two item in the `cars` array with the second one having only `refreshInterval`. Did you mean to have two cars? If so, you will need all the info for the second car.

**Comment by eengert** [comment]
Whoops, I didn't realize that extra blank vehicle would create a problem.  I used the Settings UI and must've accidentally clicked the Add to VINS button.  Removing the blank vehicle did the trick.  Thanks.
