### ISSUE TITLE
Increase ignition run time to 10 minutes which I believe is Kia maximum time allowed.  Thank you!

### ISSUE THREAD

**Issue by mbellis18** [huttotw/homebridge-kia-connect#4]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by asabatino88** [comment]
Second this - seems like a simple update to client.ts.

**Comment by asabatino88** [comment]
FYI - if you modify client.js in the compiled plugin source code you can edit the value: 5 in the following part of the code to value: 10 and have it still work:

  async startClimate(vin: string, targetTempF: string): Promise<string> {
    await this.logIn({userId: this.userId, password: this.password});
    const req: RemoteClimateRequest = {
      action: 'ACTION_EXEC_REMOTE_CLIMATE_ON',
      remoteClimate: {
        airTemp: {
          value: targetTempF,
          unit: 1,
        },
        airCtrl: true,
        defrost: false,
        ventilationWarning: false,
        ignitionOnDuration: {
          value: 5,
          unit: 4,
        },

**Comment by ultravelocity** [comment]
Thank you. I made the change locally in client.js. Would love to see some updates to this plugin.

**Comment by mbellis18** [comment]
> FYI - if you modify client.js in the compiled plugin source code you can edit the value: 5 in the following part of the code to value: 10 and have it still work:
> 
> async startClimate(vin: string, targetTempF: string): Promise { await this.logIn({userId: this.userId, password: this.password}); const req: RemoteClimateRequest = { action: 'ACTION_EXEC_REMOTE_CLIMATE_ON', remoteClimate: { airTemp: { value: targetTempF, unit: 1, }, airCtrl: true, defrost: false, ventilationWarning: false, ignitionOnDuration: { value: 5, unit: 4, },

Any chance you would be willing to walk me through how I can edit/modify the client.js?  I currently run Homebridge on an RPi4 and use the Homebridge UI to manage...  Thank you in advance for your assistance!

**Comment by ultravelocity** [comment]
I logged into the web UI, clicked on Terminal in the top right menu and went into the plugin directory:
`cd node_modules/homebridge-kia-connect/dist/kiaconnect`

Then used pico to edit the js file:
`pico client.js`

Use the cursor keys to go down to startClimate -> ignitionOnDuration and change it from 5 to 10.
Then ctrl-x to exit and save the file.

Hope that helps!
